### ISSUE TITLE
Wrong module path in go.mod

### ISSUE THREAD

**Issue by gudvinr** [Philipp15b/go-steam#115] opened 2021-03-24 23:27 UTC
As per documention:
> If the module is released at major version 2 or higher, the module path must end with a major version suffix

Since go-steam has `go.mod` file at git tag `v2.0.0` it must have `module github.com/Philipp15b/go-steam/v2` in `go.mod` and not `module github.com/Philipp15b/go-steam`.

Because of that it cannot be shown in htttps://pkg.go.dev/ for example.

**Comment by Philipp15b** [comment] 2021-04-18 12:21
I'm not quite sure how to fix this (go modules are somewhat new to me). I want to avoid copying everything in a new `v2` subfolder - this is what I believe Git is for. If you have an easy fix, I would very much appreciate a pull request.

**Comment by Jleagle** [comment] 2021-04-18 17:07
If you are referring to this https://blog.golang.org/v2-go-modules#TOC_4. I don't believe this is the suggested way of doing it. I have never seen a project with a v2 directory. I believe just adding /v2 to the URL in your go.mod should do it.

**Comment by gudvinr** [comment] 2021-04-18 17:21
Also replacing `github.com/Philipp15b/go-steam` with `github.com/Philipp15b/go-steam/v2` in import path is necessary too.  
`etcd` is suffering from this too since they added `go.mod` in v3.3 and didn't fix import path up until v3.5

**Comment by Philipp15b** [comment] 2021-04-19 05:23
Thank you both! @gudvinr You mean replacing the import path in every single file that uses it?

What do you both think about just using versions like `1.x`, removing version 2.0? It's a hack, but avoids a lot of ridiculously unnecessary work IMHO.

**Comment by gudvinr** [comment] 2021-04-19 08:33
> Thank you both! @gudvinr You mean replacing the import path in every single file that uses it?

That's correct

> What do you both think about just using versions like 1.x, removing version 2.0

If v2 contains breaking changes, it'll break working code for v1 users after update. It should be safe to do so if it's not.  
Right now there should be a little to no v2 users since `go get` should pull v1 because v2.0.0 tag does not have a proper module.

In theory you only need to replace import path in the library itself. Right now v2 can only be fetched either for users who use older Go version or if person manages to get code from master branch.

If v2 contains backward incompatible changes it is not unnecessary work though

**Comment by Jleagle** [comment] 2021-04-19 11:51
https://github.com/Philipp15b/go-steam/pull/116

**Comment by Philipp15b** [comment] 2021-04-20 06:34
Well technically v2 contains breaking changes against v1, but those changes were already a few years old at that point. I will merge #116 though.

**Comment by Jleagle** [comment] 2021-04-24 17:21
@Philipp15b Hey, any word on merging this in?

**Comment by Philipp15b** [comment] 2021-04-24 17:44
Merged it now, thanks for the reminder.

**Closed** 2021-04-24 17:43 UTC
Labels: bug, help wanted

**Comment by gudvinr** [comment] 2021-04-27 19:20
@Philipp15b I also suggest you to add [retraction](https://golang.org/ref/mod#go-mod-file-retract) for `v2.0.0` and tag last commit with `v2.0.1` or something like that.

It will instruct go tools to avoid `v2.0.0` which contains malformed `go.mod` anyway and `v2.0.1` can be finally retrieved through `go get` like you would usually do

**Comment by Philipp15b** [comment] 2021-05-01 11:06
@gudvinr Thanks for the pointer. I have just released https://github.com/Philipp15b/go-steam/releases/tag/v2.0.1. Hopefully everything finally works as intended.

**Comment by gudvinr** [comment] 2021-05-05 14:32
> Hopefully everything finally works as intended.

[pkg.go.dev](https://pkg.go.dev/github.com/Philipp15b/go-steam/v2) now showing correct version:
```
Version: v2.0.1 Latest
Published: May 1, 2021
```
