### ISSUE TITLE
Can the internal package be renamed?

### ISSUE THREAD

**Issue by Gacnt** [Philipp15b/go-steam#62] opened 2016-01-01 07:17 UTC
Can't use Gamecoordinator or Steamlang package because of the semantic meaning `internal` now has in Go. Any information would be fantastic or proposed work arounds. Thanks.

**Comment by Philipp15b** [comment] 2016-01-06 21:35
Duplicate of #57.

**Closed by Philipp15b** 2016-01-06 21:35 UTC
